---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: toolchain-cd-listener
spec:
  serviceAccountName: pipeline
  triggers:
  - name: toolchain-cd-pipeline
    binding:
      name: toolchain-cd-pipeline-binding
    template:
      name: toolchain-cd-pipeline-template
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: toolchain-cd-eventlistener
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: el-toolchain-cd-listener
    weight: 100