apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: create-github-status-task
spec:
  inputs:
    params:
    - name: repo
      description: The repo to publish the status update for e.g. tektoncd/triggers
      type: string
    - name: commit-sha
      description: The specific commit to report a status for.
      type: string
    - name: state
      description: The state to report error, failure, pending, or success.
      type: string
    - name: target-url
      type: string
      default: ""
      description: The target URL to associate with this status.
    - name: description
      type: string
      description: A short description of the status.
    - name: context
      type: string
      description: A string label to differentiate this status from the status of other systems.
  steps:
  - name: start-status
    image: quay.io/kmcdermo/github-tool:latest
    workingDir: /workspace/source
    env:
    - name: GITHUB_TOKEN
      valueFrom:
        secretKeyRef:
          name: webhook-secret
          key: token
    command: ["github-tool"]
    args:
    - "create-status"
    - "--repo"
    - "$(inputs.params.repo)"
    - "--sha"
    - "$(inputs.params.commit-sha)"
    - "--state"
    - "$(inputs.params.state)"
    - "--target-url"
    - "$(inputs.params.target-url)"
    - "--description"
    - "$(inputs.params.description)"
    - "--context"
    - "$(inputs.params.context)"